# Generated by Django 2.2.12 on 2020-11-09 16:45

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20201109_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='body_de',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='title_de',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
