# Generated by Django 2.2.12 on 2020-11-09 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tender',
            name='items',
        ),
    ]
